title: SwiftUI 3 - AsyncImage with Dyanmic Codable Session
description: iOS15 gave us a new view called AsyncImage. This view has been around for a long time in flutter, called NetworkImage. This allows you to fetch an image from the internet in real time while also showing preview and error views if anything were to go wrong.
image: https://github.com/jake-landersweb/code_vault/blob/4e129e9b2b9a62f526ccdc6ad52801f2996a9b82/asyncImage_swiftUI/assets/code.png
tags: swift,swiftui,mobile,app,application,xcode,ios,iphone,swiftui3,image,async,imageview
