title: "SwiftUI Vs Flutter: Profile View"
description: "I built a profile page in SwiftUI and Flutter, let's compare the differences"
tags: "swiftui,flutter,dart,mobile"
video: "https://www.youtube.com/watch?v=iTFN2UgeWj4"