title: Dart functions
description: A fake blog post to show some more functionality
imageUrl: https://example.com
tags: tag1,tag2,tag3,tag4
image: https://www.economist.com/img/b/1280/721/90/sites/default/files/images/2015/09/blogs/economist-explains/code2.png
